name: Update Daily Agenda

on:
  #schedule:
  #  - cron: '5 3,15 * * *'  # Roda a cada hora (ajuste conforme necessário)
  workflow_dispatch:      # Permite rodar manualmente pelo botão no GitHub

jobs:
  update-csv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas pyarrow fastparquet requests

      - name: Run update script
        env:
          VULP_TOKEN: ${{ secrets.VULP_TOKEN }}
        run: python scripts/atualiza_score_agenda.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update daily agenda scores [skip ci]" || exit 0
          git push
